var hanzikids = {   


    firstGrade : [{'char':"八", 'pinyin': "ba"},
                  {'char':"巴", 'pinyin': "ba"},
                  {'char':"比", 'pinyin': "bi"},
                  {'char':"白", 'pinyin': "bai"},
                  {'char':"百", 'pinyin': "bai"},
                  {'char':"不", 'pinyin': "bu"},
                  {'char':"草", 'pinyin': "cao"},
                  {'char':"唱", 'pinyin': "chang"},
                  {'char':"大", 'pinyin': "da"},
                  {'char':"刀", 'pinyin': "dao"},
                  {'char':"的", 'pinyin': "de"},
                  {'char':"地", 'pinyin': "di"},
                  {'char':"肚", 'pinyin': "du"},
                  {'char':"多", 'pinyin': "duo"},
                  {'char':"耳", 'pinyin': "er"},
                  {'char':"二", 'pinyin': "er"},
                  {'char':"风", 'pinyin': "feng"},
                  {'char':"工", 'pinyin': "gong"},
                  {'char':"好", 'pinyin': "hao"},
                  {'char':"禾", 'pinyin': "he"},
                  {'char':"和", 'pinyin': "he"},
                  {'char':"红", 'pinyin': "hong"},
                  {'char':"花", 'pinyin': "hua"},
                  {'char':"火", 'pinyin': "huo"},
                  {'char':"尖", 'pinyin': "jian"},
                  {'char':"见", 'pinyin': "jian"},
                  {'char':"叫", 'pinyin': "jiao"},
                  {'char':"江", 'pinyin': "jiang"},
                  {'char':"交", 'pinyin': "jiao"},
                  {'char':"九", 'pinyin': "jiu"},
                  {'char':"卡", 'pinyin': "ka"},
                  {'char':"看", 'pinyin': "kan"},
                  {'char':"口", 'pinyin': "kou"},
                  {'char':"哭", 'pinyin': "ku"},
                  {'char':"来", 'pinyin': "lai"},
                  {'char':"了", 'pinyin': "le"},
                  {'char':"李", 'pinyin': "li"},
                  {'char':"力", 'pinyin': "li"},
                  {'char':"立", 'pinyin': "li"},
                  {'char':"林", 'pinyin': "lin"},
                  {'char':"六", 'pinyin': "liu"},
                  {'char':"没", 'pinyin': "mei"},
                  {'char':"米", 'pinyin': "mi"},
                  {'char':"明", 'pinyin': "ming"},
                  {'char':"木", 'pinyin': "mu"},
                  {'char':"目", 'pinyin': "mu"},
                  {'char':"那", 'pinyin': "na"},
                  {'char':"男", 'pinyin': "nan"},
                  {'char':"你", 'pinyin': "ni"},
                  {'char':"女", 'pinyin': "nv"},
                  {'char':"朋", 'pinyin': "peng"},
                  {'char':"七", 'pinyin': "qi"},
                  {'char':"千", 'pinyin': "qian"},
                  {'char':"去", 'pinyin': "qu"},
                  {'char':"人", 'pinyin': "ren"},
                  {'char':"日", 'pinyin': "ri"},
                  {'char':"肉", 'pinyin': "rou"},
                  {'char':"三", 'pinyin': "san"},
                  {'char':"沙", 'pinyin': "sha"},
                  {'char':"山", 'pinyin': "shan"},
                  {'char':"上", 'pinyin': "shang"},
                  {'char':"少", 'pinyin': "shao"},
                  {'char':"舌", 'pinyin': "she"},
                  {'char':"生", 'pinyin': "sheng"},
                  {'char':"十", 'pinyin': "shi"},
                  {'char':"石", 'pinyin': "shi"},
                  {'char':"是", 'pinyin': "shi"},
                  {'char':"手", 'pinyin': "shou"},
                  {'char':"水", 'pinyin': "shui"},
                  {'char':"四", 'pinyin': "si"},
                  {'char':"他", 'pinyin': "ta"},
                  {'char':"天", 'pinyin': "tian"},
                  {'char':"土", 'pinyin': "tu"},
                  {'char':"玩", 'pinyin': "wan"},
                  {'char':"位", 'pinyin': "wei"},
                  {'char':"我", 'pinyin': "wo"},
                  {'char':"五", 'pinyin': "wu"},
                  {'char':"下", 'pinyin': "xia"},
                  {'char':"象", 'pinyin': "xiang"},
                  {'char':"小", 'pinyin': "xiao"},
                  {'char':"校", 'pinyin': "xiao"},
                  {'char':"笑", 'pinyin': "xiao"},
                  {'char':"心", 'pinyin': "xin"},
                  {'char':"星", 'pinyin': "xing"},
                  {'char':"姓", 'pinyin': "xing"},
                  {'char':"雪", 'pinyin': "xue"},
                  {'char':"呀", 'pinyin': "ya"},
                  {'char':"牙", 'pinyin': "ya"},
                  {'char':"言", 'pinyin': "yan"},
                  {'char':"也", 'pinyin': "ye"},
                  {'char':"一", 'pinyin': "yi"},
                  {'char':"友", 'pinyin': "you"},
                  {'char':"有", 'pinyin': "you"},
                  {'char':"右", 'pinyin': "you"},
                  {'char':"雨", 'pinyin': "yu"},
                  {'char':"月", 'pinyin': "yue"},
                  {'char':"云", 'pinyin': "yun"},
                  {'char':"再", 'pinyin': "zai"},
                  {'char':"早", 'pinyin': "zao"},
                  {'char':"这", 'pinyin': "zhe"},
                  {'char':"正", 'pinyin': "zheng"},
                  {'char':"只", 'pinyin': "zhi"},
                  {'char':"中", 'pinyin': "zhong"},
                  {'char':"竹", 'pinyin': "zhu"},
                  {'char':"子", 'pinyin': "zi"},
                  {'char':"足", 'pinyin': "zu"},
                  {'char':"左", 'pinyin': "zuo"},
                  {'char':"坐", 'pinyin': "zuo"},
                  {'char':"走", 'pinyin': "zou"}
                ],
  

    secondGrade : [{'char':"爱", 'pinyin': "ai"}, 
                   {'char':"把", 'pinyin': "ba"},
                   {'char':"爸", 'pinyin': "ba"}, 
                   {'char':"包", 'pinyin': "bao"}, 
                   {'char':"贝", 'pinyin': "bei"}, 
                   {'char':"本", 'pinyin': "ben"}, 
                   {'char':"笔", 'pinyin': "bi"}, 
                   {'char':"猜", 'pinyin': "cai"}, 
                   {'char':"才", 'pinyin': "cai"}, 
                   {'char':"长", 'pinyin': "chang"}, 
                   {'char':"吃", 'pinyin': "chi"}, 
                   {'char':"出", 'pinyin': "chu"},
                   {'char':"春", 'pinyin': "chun"},
                   {'char':"从", 'pinyin': "cong"},
                   {'char':"到", 'pinyin': "dao"},
                   {'char':"道", 'pinyin': "dao"},
                   {'char':"得", 'pinyin': "de"},
                   {'char':"弟", 'pinyin': "di"},
                   {'char':"冬", 'pinyin': "dong"},
                   {'char':"洞", 'pinyin': "dong"},
                   {'char':"都", 'pinyin': "dou"},
                   {'char':"朵", 'pinyin': "duo"},
                   {'char':"儿", 'pinyin': "er"},
                   {'char':"方", 'pinyin': "fang"},
                   {'char':"飞", 'pinyin': "fei"},
                   {'char':"分", 'pinyin': "fen"},
                   {'char':"高", 'pinyin': "gao"},
                   {'char':"告", 'pinyin': "gao"},
                   {'char':"哥", 'pinyin': "ge"},
                   {'char':"歌", 'pinyin': "ge"},
                   {'char':"个", 'pinyin': "ge"},
                   {'char':"给", 'pinyin': "gei"},
                   {'char':"跟", 'pinyin': "geng"},
                   {'char':"果", 'pinyin': "guo"},
                   {'char':"国", 'pinyin': "guo"},
                   {'char':"还", 'pinyin': "hai"},
                   {'char':"海", 'pinyin': "hai"},
                   {'char':"合", 'pinyin': "he"},
                   {'char':"河", 'pinyin': "he"},
                   {'char':"黑", 'pinyin': "hei"},
                   {'char':"很", 'pinyin': "hen"},
                   {'char':"后", 'pinyin': "hou"},
                   {'char':"画", 'pinyin': "hua"},
                   {'char':"黄", 'pinyin': "huang"},
                   {'char':"回", 'pinyin': "hui"},
                   {'char':"会", 'pinyin': "hui"},
                   {'char':"几", 'pinyin': "ji"},
                   {'char':"家", 'pinyin': "jia"},
                   {'char':"进", 'pinyin': "jin"},
                   {'char':"久", 'pinyin': "jiu"},
                   {'char':"就", 'pinyin': "jiu"},
                   {'char':"开", 'pinyin': "kai"},
                   {'char':"可", 'pinyin': "ke"},
                   {'char':"快", 'pinyin': "kuai"},
                   {'char':"老", 'pinyin': "lao"},
                   {'char':"里", 'pinyin': "li"},
                   {'char':"力", 'pinyin': "li"},
                   {'char':"两", 'pinyin': "liang"},
                   {'char':"流", 'pinyin': "liu"},
                   {'char':"妈", 'pinyin': "ma"},
                   {'char':"吗", 'pinyin': "ma"},
                   {'char':"毛", 'pinyin': "mao"},
                   {'char':"么", 'pinyin': "me"},
                   {'char':"每", 'pinyin': "mei"},
                   {'char':"妹", 'pinyin': "mei"},
                   {'char':"们", 'pinyin': "men"},
                   {'char':"名", 'pinyin': "ming"},
                   {'char':"门", 'pinyin': "men"},
                   {'char':"拿", 'pinyin': "na"},
                   {'char':"奶", 'pinyin': "nai"},
                   {'char':"年", 'pinyin': "nian"},
                   {'char':"鸟", 'pinyin': "niao"},
                   {'char':"牛", 'pinyin': "niu"},
                   {'char':"爬", 'pinyin': "pa"},
                   {'char':"怕", 'pinyin': "pa"},
                   {'char':"跑", 'pinyin': "pao"},
                   {'char':"起", 'pinyin': "qi"},
                   {'char':"前", 'pinyin': "qian"},
                   {'char':"青", 'pinyin': "qing"},
                   {'char':"请", 'pinyin': "qing"},
                   {'char':"如", 'pinyin': "ru"},
                   {'char':"入", 'pinyin': "ru"},
                   {'char':"什", 'pinyin': "shen"},
                   {'char':"谁", 'pinyin': "shei"},
                   {'char':"书", 'pinyin': "shu"},
                   {'char':"说", 'pinyin': "shuo"},
                   {'char':"送", 'pinyin': "song"},
                   {'char':"速", 'pinyin': "su"},
                   {'char':"太", 'pinyin': "tai"},
                   {'char':"跳", 'pinyin': "tiao"},
                   {'char':"同", 'pinyin': "tong"},
                   {'char':"蛙", 'pinyin': "wa"},
                   {'char':"外", 'pinyin': "wai"},
                   {'char':"为", 'pinyin': "wei"},
                   {'char':"问", 'pinyin': "wen"},
                   {'char':"午", 'pinyin': "wu"},
                   {'char':"先", 'pinyin': "xian"},
                   {'char':"想", 'pinyin': "xiang"},
                   {'char':"新", 'pinyin': "xin"},
                   {'char':"信", 'pinyin': "xin"},
                   {'char':"学", 'pinyin': "xue"},
                   {'char':"言", 'pinyin': "yan"},
                   {'char':"羊", 'pinyin': "yang"},
                   {'char':"要", 'pinyin': "yao"},
                   {'char':"以", 'pinyin': "yi"},
                   {'char':"用", 'pinyin': "yong"},
                   {'char':"游", 'pinyin': "you"},
                   {'char':"又", 'pinyin': "you"},
                   {'char':"鱼", 'pinyin': "yu"},
                   {'char':"再", 'pinyin': "zai"},
                   {'char':"怎", 'pinyin': "zen"},
                   {'char':"找", 'pinyin': "zhao"},
                   {'char':"真", 'pinyin': "zhen"},
                   {'char':"知", 'pinyin': "zhi"},
                   {'char':"只", 'pinyin': "zhi"},
                   {'char':"住", 'pinyin': "zhu"},
                   {'char':"子", 'pinyin': "zi"}

    ],

    thirdGrade : [{'char':"半", 'pinyin': "ban"},
                  {'char':"边", 'pinyin': "bian"},
                  {'char':"表", 'pinyin': "biao"},
                  {'char':"北", 'pinyin': "bei"},
                  {'char':"比", 'pinyin': "bi"},
                  {'char':"常", 'pinyin': "chang"},
                  {'char':"场", 'pinyin': "chang"},
                  {'char':"车", 'pinyin': "che"},
                  {'char':"成", 'pinyin': "cheng"},
                  {'char':"城", 'pinyin': "cheng"},
                  {'char':"厨", 'pinyin': "chu"},
                  {'char':"川", 'pinyin': "chuan"},
                  {'char':"穿", 'pinyin': "chuan"},
                  {'char':"窗", 'pinyin': "chuang"},
                  {'char':"床", 'pinyin': "chuang"},
                  {'char':"吹", 'pinyin': "chui"},
                  {'char':"次", 'pinyin': "ci"},
                  {'char':"囱", 'pinyin': "cong"},
                  {'char':"村", 'pinyin': "cun"},
                  {'char':"存", 'pinyin': "cun"},
                  {'char':"打", 'pinyin': "da"},
                  {'char':"带", 'pinyin': "dai"},
                  {'char':"等", 'pinyin': "deng"},
                  {'char':"点", 'pinyin': "dian"},
                  {'char':"电", 'pinyin': "dian"},
                  {'char':"掉", 'pinyin': "diao"},
                  {'char':"定", 'pinyin': "ding"},
                  {'char':"东", 'pinyin': "dong"},
                  {'char':"动", 'pinyin': "dong"},
                  {'char':"豆", 'pinyin': "dou"},
                  {'char':"对", 'pinyin': "dui"},
                  {'char':"发", 'pinyin': "fa"},
                  {'char':"饭", 'pinyin': "fan"},
                  {'char':"方", 'pinyin': "fang"},
                  {'char':"房", 'pinyin': "fang"},
                  {'char':"放", 'pinyin': "fang"},
                  {'char':"非", 'pinyin': "fei"},
                  {'char':"公", 'pinyin': "gong"},
                  {'char':"瓜", 'pinyin': "gua"},
                  {'char':"怪", 'pinyin': "guai"},               
                  {'char':"国", 'pinyin': "guo"},
                  {'char':"行", 'pinyin': "hang"},
                  {'char':"候", 'pinyin': "hou"},
                  {'char':"户", 'pinyin': "hu"},
                  {'char':"化", 'pinyin': "hua"},
                  {'char':"活", 'pinyin': "huo"},
                  {'char':"己", 'pinyin': "ji"},
                  {'char':"记", 'pinyin': "ji"},
                  {'char':"间", 'pinyin': "jian"},
                  {'char':"巾", 'pinyin': "jin"},
                  {'char':"今", 'pinyin': "jin"},
                  {'char':"金", 'pinyin': "jin"},
                  {'char':"界", 'pinyin': "jie"},
                  {'char':"井", 'pinyin': "jing"},
                  {'char':"具", 'pinyin': "ju"},
                  {'char':"经", 'pinyin': "jing"},
                  {'char':"客", 'pinyin': "ke"},
                  {'char':"空", 'pinyin': "kong"},
                  {'char':"拉", 'pinyin': "la"},
                  {'char':"乐", 'pinyin': "le"},
                  {'char':"累", 'pinyin': "lei"},
                  {'char':"冷", 'pinyin': "leng"},
                  {'char':"亮", 'pinyin': "liang"},
                  {'char':"楼", 'pinyin': "lou"},
                  {'char':"路", 'pinyin': "lu"},
                  {'char':"落", 'pinyin': "luo"},
                  {'char':"买", 'pinyin': "mai"},
                  {'char':"卖", 'pinyin': "mai"},
                  {'char':"美", 'pinyin': "mei"},
                  {'char':"面", 'pinyin': "mian"},
                  {'char':"民", 'pinyin': "min"},
                  {'char':"南", 'pinyin': "nan"},
                  {'char':"能", 'pinyin': "neng"},
                  {'char':"农", 'pinyin': "nong"},
                  {'char':"片", 'pinyin': "pian"},
                  {'char':"平", 'pinyin': "ping"},
                  {'char':"其", 'pinyin': "qi"},
                  {'char':"奇", 'pinyin': "qi"},
                  {'char':"气", 'pinyin': "qi"},
                  {'char':"钱", 'pinyin': "qian"},
                  {'char':"秋", 'pinyin': "qiu"},
                  {'char':"全", 'pinyin': "quan"},
                  {'char':"热", 'pinyin': "re"},
                  {'char':"色", 'pinyin': "se"},
                  {'char':"身", 'pinyin': "shen"},
                  {'char':"升", 'pinyin': "sheng"},
                  {'char':"时", 'pinyin': "shi"},
                  {'char':"食", 'pinyin': "shi"},
                  {'char':"事", 'pinyin': "shi"},
                  {'char':"示", 'pinyin': "shi"},
                  {'char':"世", 'pinyin': "shi"},
                  {'char':"市", 'pinyin': "shi"},
                  {'char':"丝", 'pinyin': "si"},
                  {'char':"收", 'pinyin': "shou"},
                  {'char':"数", 'pinyin': "shu"},
                  {'char':"抬", 'pinyin': "tai"},
                  {'char':"台", 'pinyin': "tai"},
                  {'char':"头", 'pinyin': "tou"},
                  {'char':"完", 'pinyin': "wan"},
                  {'char':"晚", 'pinyin': "wan"},
                  {'char':"王", 'pinyin': "wang"},
                  {'char':"忘", 'pinyin': "wang"},
                  {'char':"文", 'pinyin': "wen"},
                  {'char':"物", 'pinyin': "wu"},
                  {'char':"现", 'pinyin': "xian"},
                  {'char':"像", 'pinyin': "xiang"},
                  {'char':"西", 'pinyin': "xi"},
                  {'char':"洗", 'pinyin': "xi"},
                  {'char':"写", 'pinyin': "xie"},
                  {'char':"谢", 'pinyin': "xie"},
                  {'char':"星", 'pinyin': "xing"},
                  {'char':"许", 'pinyin': "xu"},
                  {'char':"亚", 'pinyin': "ya"},
                  {'char':"眼", 'pinyin': "yan"},
                  {'char':"洋", 'pinyin': "yang"},
                  {'char':"阳", 'pinyin': "yang"},
                  {'char':"样", 'pinyin': "yang"},
                  {'char':"咬", 'pinyin': "yao"},
                  {'char':"衣", 'pinyin': "yi"},
                  {'char':"椅", 'pinyin': "yi"},
                  {'char':"银", 'pinyin': "yin"},
                  {'char':"原", 'pinyin': "yuan"},
                  {'char':"于", 'pinyin': "yu"},
                  {'char':"玉", 'pinyin': "yu"},
                  {'char':"元", 'pinyin': "yuan"},
                  {'char':"院", 'pinyin': "yuan"},
                  {'char':"自", 'pinyin': "zi"},
                  {'char':"站", 'pinyin': "zhan"},
                  {'char':"只", 'pinyin': "zhi"},
                  {'char':"种", 'pinyin': "zhong"},
                  {'char':"州", 'pinyin': "zhou"},
                  {'char':"洲", 'pinyin': "zhou"},
                  {'char':"桌", 'pinyin': "zhuo"},
                  {'char':"最", 'pinyin': "zui"},
                  {'char':"做", 'pinyin': "zuo"}
    ],

    fourthGrade : [{'char':"安", 'pinyin': "an"},
                 {'char':"抱", 'pinyin': "bao"},
                 {'char':"变", 'pinyin': "bian"},
                 {'char':"便", 'pinyin': "bian"},
                 {'char':"别", 'pinyin': "bie"},
                 {'char':"冰", 'pinyin': "bing"},
                 {'char':"病", 'pinyin': "bing"},
                 {'char':"菜", 'pinyin': "cai"},
                 {'char':"参", 'pinyin': "can"},
                 {'char':"吵", 'pinyin': "chao"},
                 {'char':"充", 'pinyin': "chong"},
                 {'char':"处", 'pinyin': "chu"},
                 {'char':"错", 'pinyin': "cuo"},
                 {'char':"聪", 'pinyin': "cong"},
                 {'char':"答", 'pinyin': "da"},
                 {'char':"代", 'pinyin': "dai"},
                 {'char':"但", 'pinyin': "dan"},
                 {'char':"当", 'pinyin': "dang"},
                 {'char':"倒", 'pinyin': "dao"},
                 {'char':"到", 'pinyin': "dao"},
                 {'char':"第", 'pinyin': "di"},
                 {'char':"饿", 'pinyin': "e"},
                 {'char':"恩", 'pinyin': "en"},
                 {'char':"而", 'pinyin': "er"},
                 {'char':"法", 'pinyin': "fa"},
                 {'char':"饭", 'pinyin': "fan"},
                 {'char':"肥", 'pinyin': "fei"},
                 {'char':"感", 'pinyin': "gan"},
                 {'char':"各", 'pinyin': "ge"},
                 {'char':"更", 'pinyin': "geng"},
                 {'char':"弓", 'pinyin': "gong"},
                 {'char':"古", 'pinyin': "gu"},
                 {'char':"光", 'pinyin': "guang"},
                 {'char':"锅", 'pinyin': "guo"},
                 {'char':"忽", 'pinyin': "hu"},
                 {'char':"虎", 'pinyin': "hu"},
                 {'char':"欢", 'pinyin': "huan"},
                 {'char':"机", 'pinyin': "ji"},
                 {'char':"极", 'pinyin': "ji"},
                 {'char':"急", 'pinyin': "ji"},
                 {'char':"季", 'pinyin': "ji"},
                 {'char':"加", 'pinyin': "jia"},
                 {'char':"假", 'pinyin': "jia"},
                 {'char':"剪", 'pinyin': "jian"},
                 {'char':"教", 'pinyin': "jiao"},
                 {'char':"饺", 'pinyin': "jiao"},
                 {'char':"觉", 'pinyin': "jiao"},
                 {'char':"节", 'pinyin': "jie"},
                 {'char':"结", 'pinyin': "jie"},
                 {'char':"紧", 'pinyin': "jing"},
                 {'char':"近", 'pinyin': "jing"},
                 {'char':"经", 'pinyin': "jing"},
                 {'char':"举", 'pinyin': "ju"},
                 {'char':"句", 'pinyin': "ju"},
                 {'char':"军", 'pinyin': "jun"},
                 {'char':"考", 'pinyin': "kao"},
                 {'char':"靠", 'pinyin': "kao"},
                 {'char':"颗", 'pinyin': "ke"},
                 {'char':"理", 'pinyin': "li"},
                 {'char':"脸", 'pinyin': "lian"},
                 {'char':"料", 'pinyin': "liao"},
                 {'char':"麦", 'pinyin': "mai"},
                 {'char':"满", 'pinyin': "man"},
                 {'char':"忙", 'pinyin': "mang"},
                 {'char':"冒", 'pinyin': "mao"},
                 {'char':"帽", 'pinyin': "mao"},
                 {'char':"闹", 'pinyin': "nao"},
                 {'char':"念", 'pinyin': "nian"},
                 {'char':"排", 'pinyin': "pai"},
                 {'char':"胖", 'pinyin': "pang"},
                 {'char':"皮", 'pinyin': "pi"},
                 {'char':"品", 'pinyin': "pin"},
                 {'char':"其", 'pinyin': "qi"},
                 {'char':"且", 'pinyin': "qie"},
                 {'char':"清", 'pinyin': "qing"},
                 {'char':"求", 'pinyin': "qiu"},
                 {'char':"球", 'pinyin': "qiu"},
                 {'char':"取", 'pinyin': "qu"},
                 {'char':"趣", 'pinyin': "qu"},
                 {'char':"然", 'pinyin': "ran"},
                 {'char':"忍", 'pinyin': "ren"},
                 {'char':"认", 'pinyin': "ren"},
                 {'char':"赛", 'pinyin': "sai"},
                 {'char':"闪", 'pinyin': "shan"},
                 {'char':"神", 'pinyin': "shen"},
                 {'char':"声", 'pinyin': "sheng"},
                 {'char':"师", 'pinyin': "shi"},
                 {'char':"使", 'pinyin': "shi"},
                 {'char':"始", 'pinyin': "shi"},
                 {'char':"式", 'pinyin': "shi"},
                 {'char':"试", 'pinyin': "shi"},
                 {'char':"首", 'pinyin': "shou"},
                 {'char':"树", 'pinyin': "shu"},
                 {'char':"睡", 'pinyin': "shui"},
                 {'char':"思", 'pinyin': "si"},
                 {'char':"所", 'pinyin': "suo"},
                 {'char':"唐", 'pinyin': "tang"},
                 {'char':"汤", 'pinyin': "tang"},
                 {'char':"糖", 'pinyin': "tang"},
                 {'char':"逃", 'pinyin': "tao"},
                 {'char':"桃", 'pinyin': "tao"},
                 {'char':"特", 'pinyin': "te"},
                 {'char':"听", 'pinyin': "ting"},
                 {'char':"通", 'pinyin': "tong"},
                 {'char':"味", 'pinyin': "wei"},
                 {'char':"温", 'pinyin': "wen"},
                 {'char':"闻", 'pinyin': "wen"},
                 {'char':"喜", 'pinyin': "xi"},
                 {'char':"细", 'pinyin': "xi"},
                 {'char':"息", 'pinyin': "xi"},
                 {'char':"夏", 'pinyin': "xia"},
                 {'char':"孝", 'pinyin': "xiao"},
                 {'char':"想", 'pinyin': "xiang"},
                 {'char':"香", 'pinyin': "xiang"},
                 {'char':"向", 'pinyin': "xiang"},
                 {'char':"些", 'pinyin': "xie"},
                 {'char':"醒", 'pinyin': "xing"},
                 {'char':"幸", 'pinyin': "xing"},
                 {'char':"休", 'pinyin': "xiu"},
                 {'char':"药", 'pinyin': "yao"},
                 {'char':"夜", 'pinyin': "ye"},
                 {'char':"意", 'pinyin': "yi"},
                 {'char':"因", 'pinyin': "yin"},
                 {'char':"英", 'pinyin': "ying"},
                 {'char':"油", 'pinyin': "you"},
                 {'char':"游", 'pinyin': "you"},
                 {'char':"永", 'pinyin': "yong"},
                 {'char':"员", 'pinyin': "yuan"},
                 {'char':"远", 'pinyin': "yuan"},
                 {'char':"运", 'pinyin': "yun"},
                 {'char':"张", 'pinyin': "zhang"},
                 {'char':"着", 'pinyin': "zhao"},
                 {'char':"照", 'pinyin': "zhao"},
                 {'char':"者", 'pinyin': "zhe"},
                 {'char':"指", 'pinyin': "zhi"},
                 {'char':"治", 'pinyin': "zhi"},
                 {'char':"重", 'pinyin': "zhong"},
                 {'char':"舟", 'pinyin': "zhou"},
                 {'char':"煮", 'pinyin': "zhu"},
                 {'char':"祝", 'pinyin': "zhu"},
                 {'char':"抓", 'pinyin': "zhua"},
                 {'char':"追", 'pinyin': "zhui"},
                 
    ],

    getLength: function(grade){

        var gradeLength;

        switch (grade){
            case 1:
                gradeLength = this.firstGrade.length
                break;
            case 2:
                gradeLength = this.secondGrade.length
                break;
            case 3:
                gradeLength = this.thirdGrade.length
                break;
            case 4:
                gradeLength = this.fourthGrade.length
                break;
            default:
        }

        return gradeLength;
    },


    getHanzi : function(grade, index){
        var character = '';

        switch (grade){
            case 1:
                character = this.firstGrade[index].char;
                break;
            case 2:
                character = this.secondGrade[index].char;
                break;
            case 3:
                character = this.thirdGrade[index].char;
                break;
            case 4:
                character = this.fourthGrade[index].char;
                break;
            default:
        }

        return character;


    },

    getPinyin : function(grade, index) {

        var pinyin = '';

        switch (grade){
            case 1:
                pinyin = this.firstGrade[index].pinyin;
                break;
            case 2:
                pinyin = this.secondGrade[index].pinyin;
                break;
            case 3:
                pinyin = this.thirdGrade[index].pinyin;
                break;
            case 4:
                pinyin = this.fourthGrade[index].pinyin;
                break;
            default:
        }

        return pinyin;


    }

};
